# AI Resident @ AI4Bharat, IITM

#### Technical Skills: Python, R , Pytorch, KNIME , UiPath , Druid ,Tableau, Protege ,Neo4j, AWS, Nifi, HTML, JavaScript, Databases, Docker Containers
#### Research Interests: Cognitive Science, Machine Learning, Natural Language Processing, Social Sciences
#### Patterns & Practices:  Object Oriented Programming, Data Structures, Graph algorithms , Data modelling, Problem solving, Market Research, Customer Discovery, Domain Ecosystem and Stakeholders, Business Models

## Education						       		
- M.S (Research), Data Sciences	| International Institute of Information Technology, Bangalore (_July 2023_)	 			        		
- B.Tech., Civil Engineering | Velagapudi Siddhartha Ramakrishna Engineering College (_May 2016_)

## Work Experience
** @ AI Resident @AI4Bharat (_Dec 2023 - Present_)**
- Leveraging Iterative pseudo labeling techniques to build labelled corpora for audio datasets.
- Evaluation of ASR systems for Indic languages.

** @ Research Fellow @ Data Science For Social Good, LMU Munich(_Aug 2023 - Sep 2023)**
- Developed a web application for Fire Department, Munich to help firefighters determine the areas covered with existing and planned hydrants.

** @ Project Associate @ Karnataka Data Lake (_Sep 2022 - July 2023)**
- Hands-on experience in Data Engineering and Data Modelling of Open Government Data and designing architecture for a Big Data driven Policy Support System. 
- Co-Authored 3 publications in BASE ’21, BASE ’22 and IJCAI '23 conferences.

** @ RCB Intern @ Hp R&D (_Feb 2022 - June 2022)**
- Developed Terraform modules for infrastructure dependencies and created splunk alerts and configured them for over 19 microservices built over Internet Print Protocol.

** @Software Engineer @ Tech Mahindra (_Aug 2016 - Aug 2019)**
- Team lead of 7, an UiPath developer managing and building virtual bots to reduce manual efforts and time for our customers and peers.
- Certified expertise in end-to-end development and deployment of Robotic Process Automation projects that include, requirements gathering, solution designing, coding, testing, debugging, documentation, and implementation using the UiPath tool.
- Received 'Pat on the back' award for my contributions.

## Projects
### Automatic Riddle Generation aiding Concept Attainment
[Publication](https://arxiv.org/pdf/2310.18290.pdf)

Developed an automated approach to conceptual riddle generation using Natural Language Processing and Deep learning techniques to help motivate learners in the learning content.

![Automated Conceptual Riddles](/assets/img/eeg_band_discovery.jpeg)

### HydroXplorer Application
[Github]()

Developed a web application to help firefighters determine the areas covered with existing and planned hydrants. The application has the following features
(a) Identifies accessible zones utilizing hydrant location or natural water sources.
(b) Pinpoints nearby water sources for firefighting purposes.
(c) Calculates elevation disparities between the fire location and surrounding water sources.

![HydroXplorer App](/assets/img/bike_study.jpeg)

### Advaita - Semi-Automatic Subtitle Generator (Entrepreneurial Idea)
[Github]()
[Website](https://advaita-research.blogspot.com/?m=1)
[Demo]()

Advaita  meaning Oneness in Sanskrit, aims to  achieve it by breaking language barriers in content consumption. 
We target and encourage non-English speaking audiences to consume quality content by providing regional subtitles.

![Advaita](/assets/img/bike_study.jpeg)


## Publications
1. Parasa, Niharika Sri, Chaitali Diwan, and Srinath Srinivasa. "Automatic riddle generation for learning resources." International Conference on Artificial Intelligence in Education. Cham: Springer International Publishing, 2022.
2. Bassin, P., Parasa, N. S., Srinivasa, S., & Mandyam, S. (2021, December). Big data management for policy support in sustainable development. In International Conference on Big Data Analytics (pp. 3-15). Cham: Springer International Publishing.
3. Kulkarni, A., Bassin, P., Parasa, N. S., Venugopal, V. E., Srinivasa, S., & Ramanathan, C. (2022, December). Ontology Augmented Data Lake System for Policy Support. In International Conference on Big Data Analytics (pp. 3-16). Cham: Springer Nature Switzerland.
4. Parasa, N. S., Diwan, C., & Srinivasa, S. (2023). An Approach to Automatically generating Riddles aiding Concept Attainment. arXiv preprint arXiv:2310.18290.
5. Rachuri, S. N., Malavalli, A., Parasa, N. S., Bassin, P., & Srinivasa, S. (2023, August). Modeling the impact of policy interventions for sustainable development. In Proceedings of the Thirty-Second International Joint Conference on Artificial Intelligence (pp. 7167-7170).

- [Personal Blog : Whatz Ma Rythm](https://niharikasriparasa.blogspot.com/)
